const fs = require('fs');
let content = fs.readFileSync('frontend/src/lib/api.ts', 'utf8');

const hrApi = "export const HrAPI: any = {\n  getDepartments: async () => (await api.get('/hr/departments')).data,\n  getEmployees: async () => (await api.get('/hr/employees')).data,\n  createEmployee: async (data: any) => (await api.post('/hr/employees', data)).data,\n  updateEmployee: async (id: string, data: any) => (await api.put('/hr/employees/' + id, data)).data,\n  registerBiometric: async (id: string, data: any) => (await api.post('/hr/employees/' + id + '/biometric', data)).data,\n  getLeaves: async () => (await api.get('/hr/leaves')).data,\n  createLeave: async (data: any) => (await api.post('/hr/leaves', data)).data,\n  getAttendances: async () => (await api.get('/hr/attendance')).data,\n  clockAttendance: async (data: any) => (await api.post('/hr/attendance/clock', data)).data,\n  getPayrolls: async () => (await api.get('/hr/payroll')).data,\n  calculatePayroll: async (employeeId: string, period: string) => (await api.post('/hr/payroll/' + employeeId + '/calculate', { period })).data,\n  postPayroll: async (id: string) => (await api.post('/hr/payroll/' + id + '/post')).data,\n};\n";

const expenseApi = "export const ExpenseAPI: any = {\n  getClaims: async (params?: any) => (await api.get('/expense', { params })).data,\n  getClaim: async (id: string) => (await api.get('/expense/' + id)).data,\n  createClaim: async (data: any) => (await api.post('/expense', data)).data,\n  submitClaim: async (id: string) => (await api.post('/expense/' + id + '/submit')).data,\n  approveClaim: async (id: string) => (await api.post('/expense/' + id + '/approve')).data,\n  postClaim: async (id: string) => (await api.post('/expense/' + id + '/post')).data,\n};\n";

const assetApi = "export const AssetAPI: any = {\n  getAssets: async () => (await api.get('/asset')).data,\n  createAsset: async (data: any) => (await api.post('/asset', data)).data,\n  requestBorrow: async (data: any) => (await api.post('/asset/borrow', data)).data,\n  approveBorrow: async (id: string) => (await api.post('/asset/borrow/' + id + '/approve')).data,\n  getAssetFinancials: async (id: string) => (await api.get('/finance/asset/' + id + '/financials')).data,\n  capitalizeAsset: async (id: string, data: any) => (await api.post('/finance/asset/' + id + '/capitalize', data)).data,\n  postDepreciation: async (id: string, period: string) => (await api.post('/finance/asset/' + id + '/depreciate', { period })).data,\n  disposeAsset: async (id: string, data: any) => (await api.post('/finance/asset/' + id + '/dispose', data)).data,\n};\n";

const approvalApi = "export const ApprovalAPI: any = {\n  getPendingApprovals: async () => (await api.get('/approval/pending')).data,\n  requestApproval: async (data: any) => (await api.post('/approval', data)).data,\n  approve: async (id: string, note?: string) => (await api.post('/approval/' + id + '/approve', { note })).data,\n  reject: async (id: string, note?: string) => (await api.post('/approval/' + id + '/reject', { note })).data,\n  cancel: async (id: string) => (await api.post('/approval/' + id + '/cancel')).data,\n};\n";

content = content.replace('export default api;', hrApi + expenseApi + assetApi + approvalApi + 'export default api;');
fs.writeFileSync('frontend/src/lib/api.ts', content);
console.log('Added new APIs to frontend/src/lib/api.ts');
