const fs = require('fs');
const lines = [];
const a = (s) => lines.push(s);
a(/**);
a( * PHASE 15D.3 - CHAMBER OPERATIONS CONNECTED UAT - Production-Safe Harness);
a( *);
a( * SAFETY ARCHITECTURE:);
a( *   Prisma: ONLY for reference entity create (TimberVariant, Warehouse, Product));
a( *   Stock:  ALL via public API (InventoryLedgerService) - adjustments + transfers);
a( *   Cleanup: try/finally guaranteed - cancel transfers, cancel adj, delete Prisma refs);
a( *   NEVER uses production stock, NEVER uses availableStock[0]);
a( *);
a( * USAGE (from backend/ directory on VPS):);
a( *   cp ../scripts/qa/test-chamber-operations-uat.ts ./test-chamber-uat.ts);
a( *   API_TOKEN="ey..." API_URL="https://api.erp.boostup.id" npx ts-node test-chamber-uat.ts);
a( *   rm test-chamber-uat.ts);
a( */);
a(`);
a(import { PrismaClient } from '@prisma/client';);
a(const prisma = new PrismaClient(););
a(const MARKER    = 'CHAMBER_UAT_' + Date.now(););
a(const API_URL   = (process.env.API_URL || 'https://api.erp.boostup.id').replace(/\\/+$/, ''););
a(const API_TOKEN = process.env.API_TOKEN || '';);
a(const THICK = 20, W = 100, L = 3000;);
a(const VOL_PER = parseFloat(((THICK * W * L) / 1_000_000_000).toFixed(9)););
a(const SEED_Q = 20, SEED_V = parseFloat((20 * VOL_PER).toFixed(6)););
a(const IN_Q   = 10, IN_V   = parseFloat((10 * VOL_PER).toFixed(6)););
a(const OUT_Q  = 5,  OUT_V  = parseFloat((5  * VOL_PER).toFixed(6)););
a(	ype Status = 'PASS' | 'FAIL' | 'SKIP';);
a(const results: { s: string; status: Status; d: string }[] = [];);
a(const rec = (s: string, status: Status, d = '') => {);
a(  results.push({ s, status, d }););
a(  const icon = status === 'PASS' ? 'OK  ' : status === 'FAIL' ? 'FAIL' : 'SKIP';);
a(  console.log('  [' + icon + '] ' + s + (d ? ': ' + d : '')););
a(};);
a(sync function apiCall(endpoint: string, method = 'GET', body?: object): Promise<any> {);
a(  const bearer = API_TOKEN.startsWith('Bearer ') ? API_TOKEN : 'Bearer ' + API_TOKEN;);
a(  const opts: any = { method, headers: { 'Content-Type': 'application/json', 'Authorization': bearer } };);
a(  if (body) opts.body = JSON.stringify(body););
a(  const res = await fetch(API_URL + endpoint, opts););
a(  if (!res.ok) {);
a(    const t = await res.text(););
a(    throw new Error('HTTP ' + res.status + ' ' + method + ' ' + endpoint + ': ' + t.slice(0, 200)););
a(  });
a(  return res.json(););
a(});
a(sync function getStock(locId: string, varId: string): Promise<{pcs:number;vol:number}|null> {);
a(  try {);
a(    const r = await apiCall('/inventory/timber-stock?locationId=' + locId););
a(    const i = (r?.items || []).find((s: any) => s.timberVariantId === varId););
a(    return i ? { pcs: i.currentPcs, vol: i.currentVolumeM3 } : null;);
a(  } catch { return null; });
a(});
a(sync function run() {);
a(  console.log('='.repeat(65)););
a(  console.log('  CHAMBER UAT -- PRODUCTION-SAFE'););
a(  console.log('  API:    ' + API_URL););
a(  console.log('  MARKER: ' + MARKER););
a(  console.log('  Token:  ' + (API_TOKEN ? '[PROVIDED]' : '[MISSING]')););
a(  console.log('='.repeat(65)););
a(  if (!API_TOKEN) { console.error('BLOCKED: Set API_TOKEN env var.'); process.exit(1); });
a(  let co: any, prod: any, vari: any, yard: any, ch: any;);
a(  let seedId = '', inId = '', outId = '', ready = false;);
a(  try { await apiCall('/inventory/warehouses'); rec('A. API connectivity', 'PASS', 'OK'); });
a(  catch (e: any) { rec('A. API connectivity', 'FAIL', e.message); await prisma.);
a($disconnect(); process.exit(1); });
a(  console.log('\\n[SETUP] Creating Prisma fixtures (reference data only)...'););
a(  try {);
a(    co = await prisma.company.findFirst(););
a(    if (!co) throw new Error('No company'););
a(    yard = await prisma.warehouse.create({ data: { company_id: co.id, code: 'YARD-' + MARKER, name: 'UAT Yard ' + MARKER } }););
a(    ch   = await prisma.warehouse.create({ data: { company_id: co.id, code: 'CH-' + MARKER, name: 'UAT Chamber ' + MARKER } }););
a(    const unit = await prisma.unit.findFirst({ where: { company_id: co.id } }););
a(    if (!unit) throw new Error('No unit'););
a(    prod = await prisma.product.create({ data: { company_id: co.id, unit_id: unit.id, name: 'UAT_PROD_' + MARKER, sku: 'UAT-SKU-' + MARKER, type: 'PRODUCT' } }););
a(    vari = await prisma.timberVariant.create({ data: { company_id: co.id, productId: prod.id, sku: 'UAT-VAR-' + MARKER, species: 'Jati_UAT', grade: 'A', thickness: THICK, width: W, length: L, volumePerPiece: VOL_PER } }););
a(    ready = true;);
a(    console.log('  OK Yard=' + yard.code + ' Chamber=' + ch.code + ' Variant=' + vari.sku););
a(  } catch (e: any) { console.error('SETUP FAILED:', e.message); await prisma.);
a($disconnect(); process.exit(1); });
a(  console.log('\\n  SAFETY GATE: Prod Variant=NO | Prod Stock=NO | Cleanup=CANCEL+DELETE\\n'););
a(  try {);
a(    const wl: any = await apiCall('/inventory/warehouses'););
a(    const ws = Array.isArray(wl) ? wl : (wl.items || wl.data || []););
a(    rec('B. Warehouse retrieval', 'PASS', ws.length + ' warehouses'););
a(    rec('C. Chamber identification', ws.filter((w: any) => w.code?.startsWith('CH-')).length > 0 ? 'PASS' : 'FAIL'););
a(    console.log('[D] Seeding via POST /inventory/adjustments...'););
a(    const adj = await apiCall('/inventory/adjustments', 'POST', {);
a(      locationId: yard.id, adjustmentDate: new Date().toISOString(), reason: 'UAT_SEED', notes: 'seed ' + MARKER,);
a(      items: [{ timberVariantId: vari.id, systemPcs: 0, physicalPcs: SEED_Q, differencePcs: SEED_Q, differenceM3: SEED_V, notes: MARKER }]);
a(    }););
a(    seedId = adj.id;);
a(    await apiCall('/inventory/adjustments/' + seedId + '/post', 'POST'););
a(    const s0 = await getStock(yard.id, vari.id););
a(    if (!s0 || s0.pcs !== SEED_Q) throw new Error('Seed expected ' + SEED_Q + ' got ' + s0?.pcs););
a(    rec('D. Stock seed via adjustment API', 'PASS', 'Yard=' + s0.pcs + ' PCS'););
a(    console.log('[E] CHAMBER IN DRAFT...'););
a(    const inTx = await apiCall('/inventory/transfers', 'POST', {);
a(      fromLocationId: yard.id, toLocationId: ch.id, transferDate: new Date().toISOString(), notes: 'UAT IN ' + MARKER,);
a(      items: [{ timberVariantId: vari.id, quantityPcs: IN_Q, volumeM3: IN_V }]);
a(    }););
a(    inId = inTx.id;);
a(    if (inTx.status !== 'DRAFT') throw new Error('Expected DRAFT got ' + inTx.status););
a(    rec('E. Chamber IN DRAFT', 'PASS', inTx.transferNumber););
a(    await apiCall('/inventory/transfers/' + inId + '/post', 'POST'););
a(    const sY1 = await getStock(yard.id, vari.id), sC1 = await getStock(ch.id, vari.id););
a(    if (!sY1 || sY1.pcs !== SEED_Q - IN_Q) throw new Error('Yard expected ' + (SEED_Q-IN_Q) + ' got ' + sY1?.pcs););
a(    if (!sC1 || sC1.pcs !== IN_Q) throw new Error('Chamber expected ' + IN_Q + ' got ' + sC1?.pcs););
a(    rec('F. POST Chamber IN', 'PASS'););
a(    rec('G. Source decrement', 'PASS', 'Yard: ' + SEED_Q + ' -> ' + sY1.pcs););
a(    rec('H. Chamber increment', 'PASS', 'Chamber: 0 -> ' + sC1.pcs););
a(    rec('I. Zero-sum after IN', (sY1.pcs + sC1.pcs) === SEED_Q ? 'PASS' : 'FAIL', sY1.pcs + '+' + sC1.pcs + '=' + SEED_Q););
a(    console.log('[J] CHAMBER OUT DRAFT...'););
a(    const outTx = await apiCall('/inventory/transfers', 'POST', {);
a(      fromLocationId: ch.id, toLocationId: yard.id, transferDate: new Date().toISOString(), notes: 'UAT OUT ' + MARKER,);
a(      items: [{ timberVariantId: vari.id, quantityPcs: OUT_Q, volumeM3: OUT_V }]);
a(    }););
a(    outId = outTx.id;);
a(    rec('J. Chamber OUT DRAFT', 'PASS', outTx.transferNumber););
a(    await apiCall('/inventory/transfers/' + outId + '/post', 'POST'););
a(    const sC2 = await getStock(ch.id, vari.id), sY2 = await getStock(yard.id, vari.id););
a(    if (!sC2 || sC2.pcs !== IN_Q - OUT_Q) throw new Error('Chamber expected ' + (IN_Q-OUT_Q) + ' got ' + sC2?.pcs););
a(    if (!sY2 || sY2.pcs !== (SEED_Q-IN_Q)+OUT_Q) throw new Error('Yard expected ' + ((SEED_Q-IN_Q)+OUT_Q) + ' got ' + sY2?.pcs););
a(    rec('K. POST Chamber OUT', 'PASS'););
a(    rec('L. Chamber decrement', 'PASS', 'Chamber: ' + IN_Q + ' -> ' + sC2.pcs););
a(    rec('M. Destination increment', 'PASS', 'Yard: -> ' + sY2.pcs););
a(    try { await apiCall('/inventory/transfers/' + outId + '/post', 'POST'); rec('N. Double POST rejected', 'FAIL', 'Expected error'); });
a(    catch { rec('N. Double POST rejected', 'PASS'); });
a(    const tv = await prisma.timberVariant.findUnique({ where: { id: vari.id } }););
a(    rec('O. TimberVariant unchanged', tv?.species === vari.species && tv?.grade === vari.grade ? 'PASS' : 'FAIL'););
a(    console.log('[P] Cancelling OUT then IN...'););
a(    await apiCall('/inventory/transfers/' + outId + '/cancel', 'POST'); outId = '';);
a(    const sC3 = await getStock(ch.id, vari.id););
a(    if (!sC3 || sC3.pcs !== IN_Q) throw new Error('After cancel OUT: Chamber expected ' + IN_Q + ' got ' + sC3?.pcs););
a(    rec('P+Q. Cancel OUT, Chamber restored', 'PASS', 'Chamber=' + sC3.pcs););
a(    await apiCall('/inventory/transfers/' + inId + '/cancel', 'POST'); inId = '';);
a(    const sFY = await getStock(yard.id, vari.id), sFC = await getStock(ch.id, vari.id););
a(    const yOK = sFY?.pcs === SEED_Q, cOK = !sFC || sFC.pcs === 0;);
a(    rec('R+S. Cancel IN, baseline restored', yOK && cOK ? 'PASS' : 'FAIL', 'Yard=' + sFY?.pcs + ' Chamber=' + (sFC?.pcs ?? 0)););
a(    rec('T. Double CANCEL', 'SKIP', 'Ref cleared after cancel'););
a(    rec('X. Final baseline reconciliation', yOK && cOK ? 'PASS' : 'FAIL', yOK && cOK ? 'All stock at baseline' : 'MISMATCH'););
a(  } catch (e: any) { rec('SCENARIO', 'FAIL', e.message); console.error('\\n  ERROR:', e.message); });
a(  finally {);
a(    console.log('\\n[CLEANUP]...'););
a(    let bad = false;);
a(    for (const [lbl, tid] of [['OUT', outId], ['IN', inId]] as [string,string][]) {);
a(      if (!tid) continue;);
a(      try { await apiCall('/inventory/transfers/' + tid + '/cancel', 'POST'); console.log('  OK cancel ' + lbl); });
a(      catch (e: any) { if (!e.message.includes('CANCELLED') && !e.message.includes('Already')) { console.error('  FAIL cancel ' + lbl + ': ' + e.message); bad = true; } });
a(    });
a(    if (seedId) {);
a(      try { await apiCall('/inventory/adjustments/' + seedId + '/cancel', 'POST'); console.log('  OK cancel adj'); });
a(      catch (e: any) { if (!e.message.includes('CANCELLED')) { console.error('  FAIL cancel adj: ' + e.message); bad = true; } });
a(    });
a(    if (ready) {);
a(      try {);
a(        const txs = await prisma.stockTransfer.findMany({ where: { notes: { contains: MARKER } } }););
a(        for (const tx of txs) { await prisma.stockTransferItem.deleteMany({ where: { stockTransferId: tx.id } }); await prisma.stockTransfer.delete({ where: { id: tx.id } }); });
a(        if (seedId) {);
a(          await prisma.stockAdjustmentItem.deleteMany({ where: { adjustmentId: seedId } }););
a(          try { await prisma.stockAdjustment.delete({ where: { id: seedId } }); } catch {});
a(        });
a(        const ss = await prisma.timberStock.findMany({ where: { timberVariantId: vari.id } }););
a(        const ids = ss.map((s: any) => s.id););
a(        if (ids.length) { await prisma.timberStockMovement.deleteMany({ where: { timberStockId: { in: ids } } }); await prisma.timberStock.deleteMany({ where: { timberVariantId: vari.id } }); });
a(        if (vari) await prisma.timberVariant.delete({ where: { id: vari.id } }););
a(        if (prod) await prisma.product.delete({ where: { id: prod.id } }););
a(        if (ch)   await prisma.warehouse.delete({ where: { id: ch.id } }););
a(        if (yard) await prisma.warehouse.delete({ where: { id: yard.id } }););
a(        console.log('  OK all Prisma refs deleted'););
a(      } catch (e: any) { console.error('  FAIL Prisma cleanup:', e.message); bad = true; });
a(    });
a(    rec('Y. UAT Cleanup', bad ? 'FAIL' : 'PASS', bad ? 'Check logs' : 'All fixtures removed'););
a(  });
a(  console.log('\\n' + '='.repeat(65)););
a(  let p = 0, f = 0;);
a(  for (const r of results) { console.log('  [' + (r.status === 'PASS' ? 'OK  ' : r.status === 'FAIL' ? 'FAIL' : 'SKIP') + '] ' + r.s + (r.d ? ': ' + r.d : '')); if (r.status === 'PASS') p++; else if (r.status === 'FAIL') f++; });
a(  const cl = results.find(r => r.s === 'Y. UAT Cleanup'););
a(  const st = cl?.status === 'FAIL' ? 'FAIL -- UAT CLEANUP FAILED' : f > 0 ? 'FAIL -- ' + (results.find(r => r.status === 'FAIL')?.s || '') : 'PASS -- PRODUCTION-SAFE CONNECTED UAT READY';);
a(  console.log('\\n  FINAL STATUS: ' + st););
a(  console.log('='.repeat(65) + '\\n'););
a(});
a(un().catch(e => { console.error('TOP-LEVEL:', e.message); process.exit(1); }).finally(() => prisma.()););
fs.writeFileSync('scripts/qa/test-chamber-operations-uat.ts', lines.join('\n'), 'utf8');
console.log('Done. Lines:', lines.length);
